
package Formularios;
import vehiculos.Cliente;
import vehiculos.Cent_Pobl;
/**
 * UNIVERSIDAD DE CUNDINAMARCA
 * Ingenieria de Sistemas
 * Estudiantes: - Leidy Arevalo
 *              - Santiago Lozano
 *              - Victor Pinzon
 * 
 * Profesor: Diego Arce
 * 
 * @author 
 * @version 1.0
 * 
 */
public class Clientes extends javax.swing.JFrame {
    Cliente mClientes = new Cliente(); //Crear constructor vacio de la clase tbCliente
    Cliente[] miListaCl = mClientes.CrudListaCliente();

    Cent_Pobl mCent_Pobl = new Cent_Pobl();
    Cent_Pobl[] miListaCP = mCent_Pobl.CrudListaCent_Pobl();
    
    boolean b;
    boolean c;
    /**
     * Creates new form FormCliente
     */
    public Clientes() {
        
        initComponents();
        this.setLocation(300,120);//En esta instancia(this)cambiar(set)la posición(Location) 
        txtCen_Pob.setVisible(false);
//.................................
        //Contador del formulario  

        b=true;
        
        for(int intcont=0; intcont < miListaCl.length; intcont++ ){
        jComboCl.addItem(miListaCl[intcont].getcons_clie()+" - "+miListaCl[intcont].getnume_iden()
        +" - "+ miListaCl[intcont].getprim_nomb()+" - "+ miListaCl[intcont].getsegu_nomb()
        +" - "+ miListaCl[intcont].getprim_apel()+" - "+ miListaCl[intcont].getsegu_apel()
        +" - "+ miListaCl[intcont].getgene_clie()+" - "+ miListaCl[intcont].getcent_pobl());    
            }
        
        for(int intcont=0; intcont < miListaCP.length-1; intcont++ ){
        cbxcen_pob.addItem(miListaCP[intcont].getcodi_pobl()+" - "+miListaCP[intcont].getnomb_pobl());  
        cbxcen_pob.setSelectedIndex(0);
            }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboCl = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumD = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtPN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSN = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSA = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtCen_Pob = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        cbxgen = new javax.swing.JComboBox<>();
        cbxcen_pob = new javax.swing.JComboBox<>();
        txtGen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jComboCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboClActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 204, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Género");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("# Documento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        txtNumD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumD, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 497, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Primer nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(txtPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Segundo nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        txtSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNActionPerformed(evt);
            }
        });
        getContentPane().add(txtSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 128, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 497, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Primer apellido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        getContentPane().add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Segundo Apellido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        txtSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSAActionPerformed(evt);
            }
        });
        getContentPane().add(txtSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 127, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 497, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Centro Poblado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        txtCen_Pob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCen_PobActionPerformed(evt);
            }
        });
        getContentPane().add(txtCen_Pob, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 10, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 497, 10));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        cbxgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        cbxgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgenActionPerformed(evt);
            }
        });
        getContentPane().add(cbxgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, -1));

        cbxcen_pob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcen_pobActionPerformed(evt);
            }
        });
        getContentPane().add(cbxcen_pob, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 180, -1));

        txtGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenActionPerformed(evt);
            }
        });
        getContentPane().add(txtGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDActionPerformed

    private void txtSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSAActionPerformed

    private void txtCen_PobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCen_PobActionPerformed
        // TODO add your handling code here:
        txtCen_Pob.setVisible(false);
    }//GEN-LAST:event_txtCen_PobActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        
        mClientes.CrudInsertarCliente( txtNumD.getText(),
                    txtPN.getText(), txtSN.getText(), txtPA.getText(), 
                    txtSA.getText(), txtGen.getText(), txtCen_Pob.getText()); //Se importa el método y los parámetros necesarios
        
        jComboCl.setSelectedIndex(mClientes.getcons_clie());
        
        txtNumD.setText(""); // Entrega el valor en los campos de texto
        txtPN.setText(""); // Entrega el valor en los campos de texto
        txtSN.setText(""); // Entrega el valor en los campos de texto
        txtPA.setText(""); // Entrega el valor en los campos de texto
        txtSA.setText(""); // Entrega el valor en los campos de texto
        txtGen.setText("");// Entrega el valor en los campos de texto
        txtCen_Pob.setText(""); // Entrega el valor en los campos de texto
        

        btnActualizar.setEnabled(false); // Se mantiene el botón actualizar como falso
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
//            FormMenuVendedor Fmenu =  new FormMenuVendedor();
//            Fmenu.setVisible(true);
//            setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jComboClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboClActionPerformed
        // TODO add your handling code here:
//          if(b){
//        Clientes[] miLista = micliente.CrudListaCliente();
//        micliente = miLista[jComboCl.getSelectedIndex()];
//        
//        txtNumD.setText(" " + micliente.getstrDocumentoIdentidad()); // Entrega el valor en los campos de texto
//        txtPN.setText(" " + micliente.getstrPrimerNombreCliente()); // Entrega el valor en los campos de texto
//        txtSN.setText(" " + micliente.getstrSegundoNombreCliente()); // Entrega el valor en los campos de texto
//        txtPA.setText(" " + micliente.getstrPrimerApellidoCliente()); // Entrega el valor en los campos de texto
//        txtSA.setText(" " + micliente.getstrSegundoApellidoCliente()); // Entrega el valor en los campos de texto
//        txtDir.setText(" " + micliente.getstrDireccionCliente()); // Entrega el valor en los campos de texto
//        txtTel.setText(" " + micliente.getstrTelefonoCliente()); // Entrega el valor en los campos de texto
//        
//        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
//        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
//        }
    }//GEN-LAST:event_jComboClActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

        mClientes.CrudActualizarCliente(mClientes.getcons_clie(),txtNumD.getText(),txtPN.getText(), txtSN.getText(), 
                txtPA.getText(),txtSA.getText(),txtGen.getText(),txtCen_Pob.getText()); //Se importa el método y los parámetros necesarios
        

        txtNumD.setText(""); // Entrega el valor en los campos de texto
        txtPN.setText(""); // Entrega el valor en los campos de texto
        txtSN.setText(""); // Entrega el valor en los campos de texto
        txtPA.setText(""); // Entrega el valor en los campos de texto
        txtSA.setText(""); // Entrega el valor en los campos de texto
        txtGen.setText("");// Entrega el valor en los campos de texto
        txtCen_Pob.setText(""); // Entrega el valor en los campos de texto
        
        btnInsertar.setEnabled(false); // Se mantiene el botón insertar como falso
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        b=false; // Se declara la variable booleana como falsa para no realizar la acción
        
        txtNumD.setText(""); // Entrega el valor en los campos de texto
        txtPN.setText(""); // Entrega el valor en los campos de texto
        txtSN.setText(""); // Entrega el valor en los campos de texto
        txtPA.setText(""); // Entrega el valor en los campos de texto
        txtSA.setText(""); // Entrega el valor en los campos de texto
        txtGen.setText(""); // Entrega el valor en los campos de texto
        txtCen_Pob.setText(""); // Entrega el valor en los campos de texto
        

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboCl.removeAllItems(); //Se limpia el formulario.
//        tbCliente[] miLista =micliente.CrudListaCliente(); 
      
//        jComboCl.addItem(miListaCl[intcont].getcons_clie()+" - "+miListaCl[intcont].getnume_iden()
//        +" - "+ miListaCl[intcont].getprim_nomb()+" - "+ miListaCl[intcont].getsegu_nomb()
//        +" - "+ miListaCl[intcont].getprim_apel()+" - "+ miListaCl[intcont].getsegu_apel()
//        +" - "+ miListaCl[intcont].getgene_clie()+" - "+ miListaCl[intcont].getcent_pobl());    
//            }
        

        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miListaCl.length; intcont++ ){
        jComboCl.addItem(miListaCl[intcont].getcons_clie()+" - "+miListaCl[intcont].getnume_iden()
         +" - "+ miListaCl[intcont].getprim_nomb()+" - "+miListaCl[intcont].getsegu_nomb()
        +" - "+ miListaCl[intcont].getprim_apel()+" - "+ miListaCl[intcont].getsegu_apel()
        +" - "+ miListaCl[intcont].getgene_clie()+" - "+ miListaCl[intcont].getcent_pobl());  
        jComboCl.setSelectedIndex(0); // Posiciona el jcombo en la posición 0
            }   
        b=true;
        
        c=false;

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        cbxcen_pob.removeAllItems(); //Se limpia el formulario.
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miListaCP.length; intcont++ ){
        cbxcen_pob.addItem(miListaCP[intcont].getcodi_pobl()+" - "+miListaCP[intcont].getnomb_pobl());  
        cbxcen_pob.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
       c=true;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbxcen_pobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcen_pobActionPerformed
        // TODO add your handling code here:
        txtCen_Pob.setText(cbxcen_pob.getSelectedItem().toString());
    }//GEN-LAST:event_cbxcen_pobActionPerformed

    private void cbxgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgenActionPerformed
        // TODO add your handling code here:
        txtGen.setText(cbxgen.getSelectedItem().toString());
    }//GEN-LAST:event_cbxgenActionPerformed

    private void txtGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenActionPerformed
        // TODO add your handling code here:
        txtGen.setVisible(false);
    }//GEN-LAST:event_txtGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxcen_pob;
    private javax.swing.JComboBox<String> cbxgen;
    private javax.swing.JComboBox jComboCl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtCen_Pob;
    private javax.swing.JTextField txtGen;
    private javax.swing.JTextField txtNumD;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPN;
    private javax.swing.JTextField txtSA;
    private javax.swing.JTextField txtSN;
    // End of variables declaration//GEN-END:variables
}
