
package Formularios;

/**
 * UNIVERSIDAD DE CUNDINAMARCA
 * Ingenieria de Sistemas
 * Estudiantes: - Leidy Arevalo
 *              - Santiago Lozano
 *              - Victor Pinzon
 * 
 * Profesor: Diego Arce
 * 
 * @author 
 * @version 1.0
 * 
 */

public class Factura extends javax.swing.JFrame {
    tbVenta miventa = new tbVenta(); //Crear constructor vacio de la clase tbVentas
    tbVenta [] miListaV =  miventa.CrudListaVenta();
    
    tbVehiculo mivehiculo = new tbVehiculo(); //Crear constructor vacio de la clase tbVehiculo
    tbVehiculo [] miListaVh =  mivehiculo.CrudListaVehiculo();

    tbCliente micliente = new tbCliente();//Crear constructor vacio de la clase tbCliente
    tbCliente [] miListaCl = micliente.CrudListaCliente();
    
    tbUsuario miusuario = new tbUsuario();//Crear constructor vacio de la clase tbUsuario
    tbUsuario [] miListaU = miusuario.CrudListaUsuario();
    
    boolean p,bv,bu,bc;
    /**
     * Creates new form FormVenta
     */
    public Factura() {
        initComponents();
        this.setLocation(300,120);//En esta instancia(this)cambiar(set)la posición(Location) 
        p=true;
        for(int intcont=0; intcont < miListaV.length; intcont++ ){
        jComboVe.addItem(miListaV[intcont].getintIdVehiculo()+" - "+ miListaV[intcont].getintIdUsuario()
                +" - "+ miListaV[intcont].getintIdCliente()+" - "+miListaV[intcont].getintIdVehiculo()
                +" "+miListaV[intcont].getintPrecioTotal()
                +" - "+miListaV[intcont].getstrFechaVenta());                
            }
        
        bu=true;
        for(int intcont=0; intcont < miListaU.length; intcont++ ){
        jComboVU.addItem(miListaU[intcont].getintIdUsuario()+" - "+miListaU[intcont].getintTipoDocumentoUsuario()
        +" - "+ miListaU[intcont].getstrDocumentoIdentidad()+" - "+ miListaU[intcont].getstrPrimerNombreUsuario()
        +" - "+ miListaU[intcont].getstrSegundoNombreUsuario()+" - "+ miListaU[intcont].getstrPrimerApellidoUsuario()
        +" - "+ miListaU[intcont].getstrSegundoApellidoUsuario()+" - "+ miListaU[intcont].getstrTelefonoUsuario()
        +" - "+ miListaU[intcont].getstrDireccionUsuario()+"");    
            } 
        
        bc=true;        
                for(int intcont=0; intcont < miListaCl.length; intcont++ ){
        jComboCl.addItem(miListaCl[intcont].getintIdCliente()+" - "+miListaCl[intcont].getintTipoDocumentoCliente()
        +" - "+ miListaCl[intcont].getstrDocumentoIdentidad()+" - "+ miListaCl[intcont].getstrPrimerNombreCliente()
        +" - "+ miListaCl[intcont].getstrSegundoNombreCliente()+" - "+ miListaCl[intcont].getstrPrimerApellidoCliente()
        +" - "+ miListaCl[intcont].getstrSegundoApellidoCliente()+" - "+ miListaCl[intcont].getstrTelefonoCliente()
        +" - "+ miListaCl[intcont].getstrDireccionCliente());    

        }
        bv=true;
        for(int intcont=0; intcont < miListaVh.length; intcont++ ){
        jComboVh.addItem(miListaVh[intcont].getintIdVehiculo()+" - "+ miListaVh[intcont].getintIdMarca() 
                +" - "+ miListaVh[intcont].getintIdEstilo()+" - "+miListaVh[intcont]
                +" - "+ miListaVh[intcont].getintTipoCombustible()+" - "+miListaVh[intcont].getintPrecio()
                +" - "+miListaVh[intcont].getstrPlaca()+" - "+miListaVh[intcont].getstrNumeroChasis()
                +" - "+miListaVh[intcont].getstrNumeroMotor()+" - "+miListaVh[intcont].getstrCilindraje()
                +" - "+miListaVh[intcont].getstrModelo()+" - "+miListaVh[intcont].getstrVersion());                
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jComboVe = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboCl = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboVh = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtPT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jComboVU = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jComboVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboVeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 17, 203, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 425, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 67, -1, -1));

        jComboCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboClActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 64, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Vehículo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 67, -1, -1));

        jComboVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboVhActionPerformed(evt);
            }
        });
        getContentPane().add(jComboVh, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 64, 151, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 425, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Precio total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 425, 10));
        getContentPane().add(txtPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 152, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Fecha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 48, 425, 10));

        jComboVU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboVUActionPerformed(evt);
            }
        });
        getContentPane().add(jComboVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Vendedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/fondo-rojo-5634.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboVhActionPerformed
        // TODO add your handling code here:
        if(bv){
        tbVehiculo[] miLista = mivehiculo.CrudListaVehiculo();
        mivehiculo = miLista[jComboVh.getSelectedIndex()];
        
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboVhActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        miventa.CrudInsertarVenta(miusuario.getintIdUsuario(),micliente.getintIdCliente(), 
                mivehiculo.getintIdVehiculo(), Integer.parseInt(" ") , Integer.parseInt(txtPT.getText()), txtFecha.getText());                                                                                                  
       
        jComboVU.setSelectedIndex(miventa.getintIdUsuario());
        jComboCl.setSelectedIndex(miventa.getintIdCliente());
        jComboVh.setSelectedIndex(miventa.getintIdVehiculo());
        txtPT.setText(" " + miventa.getintPrecioTotal());
        txtFecha.setText(" " + miventa.getstrFechaVenta());
        
        
        btnActualizar.setEnabled(false); // Se mantiene el botón actualizar como falso
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
            FormMenuVendedor Fmenu =  new FormMenuVendedor();
            Fmenu.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jComboVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboVeActionPerformed
        // TODO add your handling code here:
        if(p){
        tbVenta[] miLista = miventa.CrudListaVenta();
        miventa = miLista[jComboVe.getSelectedIndex()];
 
        txtPT.setText(" " + miventa.getintPrecioTotal());
        txtFecha.setText(" " + miventa.getstrFechaVenta());

        
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboVeActionPerformed

    private void jComboVUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboVUActionPerformed
        // TODO add your handling code here:
        if(bu){
        tbUsuario[] miLista = miusuario.CrudListaUsuario();
        miusuario = miLista[jComboVU.getSelectedIndex()];
        
        
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboVUActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int i = Integer.parseInt("");
        miventa.CrudActualizarVenta(miventa.getintIdVenta(), miusuario.getintIdUsuario(), micliente.getintIdCliente(),
                mivehiculo.getintIdColor(),i , Integer.parseInt(txtPT.getText()), txtFecha.getText()); //Se importa el método y los parámetros necesarios

        jComboVU.setSelectedIndex(miventa.getintIdUsuario());
        jComboCl.setSelectedIndex(miventa.getintIdCliente());
        jComboVh.setSelectedIndex(miventa.getintIdVehiculo());
        txtPT.setText(" " + miventa.getintPrecioTotal());
        txtFecha.setText(" " + miventa.getstrFechaVenta());      
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jComboClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboClActionPerformed
        // TODO add your handling code here:
        if(bc){
        tbCliente[] miLista = micliente.CrudListaCliente();
        micliente = miLista[jComboCl.getSelectedIndex()];
        
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboClActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        p=false; // Se declara la variable booleana como falsa para no realizar la acción       
        txtPT.setText(" " + miventa.getintPrecioTotal());
        txtFecha.setText(" " + miventa.getstrFechaVenta());

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboVe.removeAllItems(); //Se limpia el formulario.       
        tbVenta[] miLista =miventa.CrudListaVenta(); 
        // Se crea un for para borrar el formulario y que el jCombo no este vacio

        for(int intcont=0; intcont < miLista.length; intcont++ ){
        jComboVe.addItem(miLista[intcont].getintIdVehiculo()+" - "+ miLista[intcont].getintIdUsuario()
                +" - "+ miLista[intcont].getintIdCliente()+" - "+miLista[intcont].getintIdVehiculo()
                +""+miLista[intcont].getintPrecioTotal()
                +" - "+miLista[intcont].getstrFechaVenta());                
        
        jComboVh.setSelectedIndex(0); // Posiciona el jcombo en la posición 0 
            }           
        p=true;
//.......................................................................................................................
        bu=false; // Se declara la variable booleana como falsa para no realizar la acción

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboVU.removeAllItems(); //Se limpia el formulario.
        tbUsuario[] miLista2 =miusuario.CrudListaUsuario();
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista2.length; intcont++ ){
        jComboVU.addItem(miLista2[intcont].getintIdUsuario()+" - "+miLista2[intcont].getintTipoDocumentoUsuario()
        +" - "+ miLista2[intcont].getstrDocumentoIdentidad()+" - "+ miLista2[intcont].getstrPrimerNombreUsuario()
        +" - "+ miLista2[intcont].getstrSegundoNombreUsuario()+" - "+ miLista2[intcont].getstrPrimerApellidoUsuario()
        +" - "+ miLista2[intcont].getstrSegundoApellidoUsuario()+" - "+ miLista2[intcont].getstrTelefonoUsuario()
        +" - "+ miLista2[intcont].getstrDireccionUsuario()+"");   
        jComboVU.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        bu=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.......................................................................................................................        
        bc=false; // Se declara la variable booleana como falsa para no realizar la acción
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboCl.removeAllItems(); //Se limpia el formulario.
        tbCliente[] miLista3 =micliente.CrudListaCliente(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        bc=true;        
        for(int intcont=0; intcont < miListaCl.length; intcont++ ){
        jComboCl.addItem(miListaCl[intcont].getintIdCliente()+" - "+miListaCl[intcont].getintTipoDocumentoCliente()
        +" - "+ miListaCl[intcont].getstrDocumentoIdentidad()+" - "+ miListaCl[intcont].getstrPrimerNombreCliente()
        +" - "+ miListaCl[intcont].getstrSegundoNombreCliente()+" - "+ miListaCl[intcont].getstrPrimerApellidoCliente()
        +" - "+ miListaCl[intcont].getstrSegundoApellidoCliente()+" - "+ miListaCl[intcont].getstrTelefonoCliente()
        +" - "+ miListaCl[intcont].getstrDireccionCliente());       
        jComboCl.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        bc=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.......................................................................................................................
        bv=false; // Se declara la variable booleana como falsa para no realizar la acción

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboVh.removeAllItems(); //Se limpia el formulario.
        tbVehiculo[] miLista4 =mivehiculo.CrudListaVehiculo(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        bv=true;
        for(int intcont=0; intcont < miListaVh.length; intcont++ ){
        jComboVh.addItem(miListaVh[intcont].getintIdVehiculo()+" - "+ miListaVh[intcont].getintIdMarca() 
                +" - "+ miListaVh[intcont].getintIdEstilo()+" - "+miListaVh[intcont]
                +" - "+ miListaVh[intcont].getintTipoCombustible()+" - "+miListaVh[intcont].getintPrecio()
                +" - "+miListaVh[intcont].getstrPlaca()+" - "+miListaVh[intcont].getstrNumeroChasis()
                +" - "+miListaVh[intcont].getstrNumeroMotor()+" - "+miListaVh[intcont].getstrCilindraje()
                +" - "+miListaVh[intcont].getstrModelo()+" - "+miListaVh[intcont].getstrVersion());                   
        jComboVh.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        
        bv=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción

    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox jComboCl;
    private javax.swing.JComboBox jComboVU;
    private javax.swing.JComboBox jComboVe;
    private javax.swing.JComboBox jComboVh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPT;
    // End of variables declaration//GEN-END:variables
}
