/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import vehiculos.Vehiculo;
import vehiculos.Concesionario;
import javax.swing.JOptionPane;

/**
 *
 * @author peace
 */
public class FormVehiculo extends javax.swing.JFrame {

    Vehiculo mivehiculo = new Vehiculo();
    Vehiculo[] miListaVh = mivehiculo.CrudListaVehiculo();
    boolean p;
    Concesionario miconcesionario = new Concesionario();//Crear constructor vacio de la clase ctMarca
    Concesionario[] miListaC = miconcesionario.crudListaConsecionario();
    boolean c;

    /**
     * Creates new form FormVehiculo
     */
    public FormVehiculo() {
        initComponents();
        this.setLocation(300, 120);//En esta instancia(this)cambiar(set)la posición(Location)
        this.setSize(540, 480);
        //.................................
        //Contador del formulario        
        p = true;
        for (int intcont = 0; intcont < miListaVh.length; intcont++) {
            jComboVh.addItem(miListaVh[intcont].getcons_vehi() + " - " + miListaVh[intcont].getcons_cons()
                    + " - " + miListaVh[intcont].getmarc_vehi() + " - " + miListaVh[intcont].getmode_vehi()
                    + " - " + miListaVh[intcont].getline_vehi() + " - " + miListaVh[intcont].getplac_vehi()
                    + " - " + miListaVh[intcont].getcolo_vehi() + " - " + miListaVh[intcont].getestado());
        }
        c = true;
        for (int intcont = 0; intcont < miListaC.length; intcont++) {
            jComboC.addItem(miListaC[intcont].getcons_cons() + " - " + miListaC[intcont].getnomb_cons()
                    + " - " + miListaC[intcont].getcodi_pobl() + " - " + miListaC[intcont].gettele_cons()
                    + " - " + miListaC[intcont].getdire_cons()
            );
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboVh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlinea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        btninsertar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboC = new javax.swing.JComboBox<>();
        txtestado = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtconcesionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vehiculo");

        jComboVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboVhActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca");

        txtmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarcaActionPerformed(evt);
            }
        });

        jLabel3.setText("Modelo");

        txtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodeloActionPerformed(evt);
            }
        });

        jLabel4.setText("Línea");

        txtlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlineaActionPerformed(evt);
            }
        });

        jLabel5.setText("Placa");

        jLabel6.setText("Color");

        txtcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolorActionPerformed(evt);
            }
        });

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnvolver.setText("Volver");

        jLabel7.setText("Estado");

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "inactivo" }));
        jComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Concesionario");

        jComboC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCActionPerformed(evt);
            }
        });

        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtconcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconcesionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btninsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboC, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtconcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(txtlinea, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboVh, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboVh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)
                        .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsertar)
                    .addComponent(btnactualizar)
                    .addComponent(btnlimpiar)
                    .addComponent(btnvolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmarcaActionPerformed

    private void txtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodeloActionPerformed

    private void txtlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlineaActionPerformed

    private void txtcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorActionPerformed

    private void jComboVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboVhActionPerformed
        // TODO add your handling code here:
        if (p) {
            Vehiculo[] miLista = mivehiculo.CrudListaVehiculo();
            mivehiculo = miLista[jComboVh.getSelectedIndex()];

            txtmarca.setText(" " + mivehiculo.getmarc_vehi());
            txtmodelo.setText(" " + mivehiculo.getmode_vehi());
            txtlinea.setText(" " + mivehiculo.getline_vehi());
            txtplaca.setText(" " + mivehiculo.getplac_vehi());
            txtcolor.setText(" " + mivehiculo.getcolo_vehi());
            txtestado.setText(" " + mivehiculo.getestado());

            btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
            btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboVhActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
        Realizado e = new Realizado();
        FormVehiculo h = new FormVehiculo();

        e.setVisible(true);
        h.setVisible(false);
        setVisible(false);

        mivehiculo.CrudInsertarVehiculo(miconcesionario.getcons_cons(), txtmarca.getText(), txtmodelo.getText(), txtlinea.getText(),
                txtplaca.getText(), txtcolor.getText(), txtestado.getText());

        txtconcesionario.setText("");
        txtmarca.setText(""); // Entrega el valor en los campos de texto  
        txtmodelo.setText(""); // Entrega el valor en los campos de texto
        txtlinea.setText(""); // Entrega el valor en los campos de texto
        txtplaca.setText(""); // Entrega el valor en los campos de texto
        txtcolor.setText(""); // Entrega el valor en los campos de texto
        txtestado.setText(""); // Entrega el valor en los campos de texto

        btnactualizar.setEnabled(false); // Se mantiene el botón actualizar como falso
    }//GEN-LAST:event_btninsertarActionPerformed

    private void jComboCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCActionPerformed
        // TODO add your handling code here:
        if (c) {
            txtconcesionario.setText(jComboC.getSelectedItem().toString());
            Concesionario[] miLista = miconcesionario.crudListaConsecionario();
            miconcesionario = miLista[jComboC.getSelectedIndex()];
            btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
            btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }


    }//GEN-LAST:event_jComboCActionPerformed

    private void jComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstadoActionPerformed
        // TODO add your handling code here:
        txtestado.setText(jComboEstado.getSelectedItem().toString());
    }//GEN-LAST:event_jComboEstadoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        Realizado e = new Realizado();
        FormVehiculo h = new FormVehiculo();

        e.setVisible(true);
        h.setVisible(false);
        setVisible(false);
        mivehiculo.CrudActualizarVehiculo(jComboVh.getSelectedIndex(), jComboC.getSelectedIndex(),
                txtmarca.getText(), txtmodelo.getText(), txtlinea.getText(), txtplaca.getText(), txtcolor.getText(), txtestado.getText()); //Se importa el método y los parámetros necesarios

        txtconcesionario.setText("");
        txtmarca.setText(""); // Entrega el valor en los campos de texto
        txtmodelo.setText(""); // Entrega el valor en los campos de texto  
        txtlinea.setText(""); // Entrega el valor en los campos de texto
        txtplaca.setText(""); // Entrega el valor en los campos de texto
        txtcolor.setText(""); // Entrega el valor en los campos de texto
        txtestado.setText(""); // Entrega el valor en los campos de texto

        btninsertar.setEnabled(false); // Se mantiene el botón actualizar como falso  
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        Realizado e = new Realizado();
        FormVehiculo h = new FormVehiculo();

        e.setVisible(true);
        h.setVisible(false);
        setVisible(false);

        p = false; // Se declara la variable booleana como falsa para no realizar la acción       
        txtmarca.setText(""); // Entrega el valor en los campos de texto
        txtmodelo.setText(""); // Entrega el valor en los campos de texto  
        txtlinea.setText(""); // Entrega el valor en los campos de texto
        txtplaca.setText(""); // Entrega el valor en los campos de texto
        txtcolor.setText(""); // Entrega el valor en los campos de texto
        txtestado.setText(""); // Entrega el valor en los campos de texto

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero

        jComboVh.removeAllItems(); //Se limpia el formulario.       
        Vehiculo[] miLista = mivehiculo.CrudListaVehiculo();
        // Se crea un for para borrar el formulario y que el jCombo no este vacio

        for (int intcont = 0; intcont < miLista.length; intcont++) {
            jComboVh.addItem(miLista[intcont].getcons_vehi() + " - " + miLista[intcont].getmarc_vehi()
                    + " - " + miLista[intcont].getmode_vehi() + " - " + miLista[intcont].getline_vehi()
                    + " - " + miLista[intcont].getplac_vehi() + " - " + miLista[intcont].getcolo_vehi()
                    + " - " + miLista[intcont].getestado());
            jComboVh.setSelectedIndex(0); // Posiciona el jcombo en la posición 0 
        }
        p = true;
//.......................................................................................................................
        c = false; // Se declara la variable booleana como falsa para no realizar la acción

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero

        jComboC.removeAllItems(); //Se limpia el formulario.
        Concesionario[] miLista2 = miconcesionario.crudListaConsecionario();

        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for (int intcont = 0; intcont < miLista2.length; intcont++) {
            jComboC.addItem(miListaC[intcont].getcons_cons() + " - " + miListaC[intcont].getnomb_cons()
                    + " - " + miListaC[intcont].getcodi_pobl() + " - " + miListaC[intcont].gettele_cons()
                    + " - " + miListaC[intcont].getdire_cons());
            jComboC.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
        }
        c = true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        mivehiculo.CrudBuscarVehiculo((Integer.parseInt(txtbuscar.getText())));

        jComboC.setSelectedIndex(miconcesionario.getcons_cons());
        txtmarca.setText(mivehiculo.getmarc_vehi());
        txtmodelo.setText(mivehiculo.getmode_vehi());
        txtlinea.setText(mivehiculo.getline_vehi());
        txtplaca.setText(mivehiculo.getplac_vehi());
        txtcolor.setText(mivehiculo.getcolo_vehi());
        jComboEstado.setSelectedIndex(0);

        btninsertar.setEnabled(false);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtconcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconcesionarioActionPerformed
        // TODO add your handling code here:

        txtconcesionario.setText(jComboC.getSelectedItem().toString());

    }//GEN-LAST:event_txtconcesionarioActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> jComboC;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JComboBox<String> jComboVh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtconcesionario;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtlinea;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
