/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.awt.Color;
import vehiculos.Factura;
import vehiculos.Concesionario;
import vehiculos.Cliente;
import vehiculos.Vendedor;
import vehiculos.Vehiculo;
import javax.swing.JOptionPane;
/**
 *
 * @author peace
 */
public class FormFactura extends javax.swing.JFrame {
    Factura mif = new Factura(); //Crear constructor vacio de la clase tbVehiculo
    Factura [] miListaf =  mif.CrudListaFactura();

    Concesionario mic = new Concesionario();//Crear constructor vacio de la clase ctMarca
    Concesionario [] miListac = mic.crudListaConsecionario();
    
    Cliente micl = new Cliente();//Crear constructor vacio de la clase ctEstilo
    Cliente [] miListacl = micl.CrudListaCliente();
    
    Vendedor miv = new Vendedor();//Crear constructor vacio de la clase ctColor
    Vendedor [] miListav = miv.crudListaVend();
    
    Vehiculo mivh = new Vehiculo();//Crear constructor vacio de la clase ctTipoCombustible
    Vehiculo [] miListavh = mivh.CrudListaVehiculo();
    
    boolean f,c,cl,v,vh;
    /**
     * Creates new form FormFactura
     */
    public FormFactura() {
        initComponents();
        this.setLocation(300,120);//En esta instancia(this)cambiar(set)la posición(Location)
        this.setSize(540,420);
    
//.................................
        //Contador del formulario   
        f=true;
        for(int intcont=0; intcont < miListaf.length; intcont++ ){
        jCombof.addItem(miListaf[intcont].getcons_fact()+" - "+ miListaf[intcont].getnume_fact()
                +" - "+ miListaf[intcont].getfech_fact()+" - "+ miListaf[intcont].getcons_clie()
                +" - "+ miListaf[intcont].getcons_vend()+" - "+" - "+miListaf[intcont].getcons_cons()
                +" - "+miListaf[intcont].getcons_vehi()+" - "+miListaf[intcont].getestado());                
            }
        
        cl=true;
        for(int intcont=0; intcont < miListacl.length; intcont++ ){
        jCombocl.addItem(miListacl[intcont].getcons_clie()+" - "+miListacl[intcont].getprim_nomb()+" - "
         + miListacl[intcont].getprim_apel()+ miListacl[intcont].getcent_pobl()+ miListacl[intcont].getestado());  
            }
        
        v=true;        
        for(int intcont=0; intcont < miListav.length; intcont++ ){
        jCombov.addItem(miListav[intcont].getIntConsVend()+ miListav[intcont].getStringNomVend());  

            }
        
        c=true;
        for(int intcont=0; intcont < miListac.length; intcont++ ){
        jComboc.addItem(miListac[intcont].getcons_cons()+" - "+miListac[intcont].getdire_cons()+ miListac[intcont].getestado());

            }
        
        vh=true;
        for(int intcont=0; intcont < miListavh.length; intcont++ ){
        jCombovh.addItem(miListavh[intcont].getmarc_vehi()+" - "+miListavh[intcont].getmode_vehi()+ miListavh[intcont].getplac_vehi()
                + miListavh[intcont].getcolo_vehi() + miListavh[intcont].getestado());    

            }
        }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCombof = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboestado = new javax.swing.JComboBox<>();
        txtestado = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnumfact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCombocl = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCombov = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCombovh = new javax.swing.JComboBox<>();
        btninsertar = new javax.swing.JButton();
        txtc = new javax.swing.JTextField();
        txtv = new javax.swing.JTextField();
        txtcons = new javax.swing.JTextField();
        txtvh = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Factura");

        jCombof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombofActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado");

        jComboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jComboestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboestadoActionPerformed(evt);
            }
        });

        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("# Factura");

        txtnumfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumfactActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha");

        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente");

        jCombocl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboclActionPerformed(evt);
            }
        });

        jLabel7.setText("Vendedor");

        jCombov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombovActionPerformed(evt);
            }
        });

        jLabel8.setText("Concesionario");

        jComboc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombocActionPerformed(evt);
            }
        });

        jLabel9.setText("Vehículo");

        jCombovh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombovhActionPerformed(evt);
            }
        });

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        txtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcActionPerformed(evt);
            }
        });

        txtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvActionPerformed(evt);
            }
        });

        txtcons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsActionPerformed(evt);
            }
        });

        txtvh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvhActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnvolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCombof, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btninsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlimpiar)
                        .addGap(50, 50, 50)
                        .addComponent(btnvolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnumfact, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCombocl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCombov, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCombovh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCombof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnumfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCombocl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCombov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCombovh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsertar)
                    .addComponent(btnactualizar)
                    .addComponent(btnlimpiar)
                    .addComponent(btnvolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumfactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumfactActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void jCombofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombofActionPerformed
        // TODO add your handling code here:
        if(f){
        Factura[] miLista = mif.CrudListaFactura();
        mif = miLista[jCombof.getSelectedIndex()];

        txtnumfact.setText(mif.getnume_fact());
        txtfecha.setText(mif.getfech_fact());
        txtc.setText(" " + mif.getcons_clie());
        txtv.setText(" " + mif.getcons_vend());
        txtcons.setText(" " + mif.getcons_cons());
        txtvh.setText(" " + mif.getcons_vehi());
        txtestado.setText(" " + mif.getestado());
        
        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jCombofActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
        mif.CrudInsertarFactura(txtnumfact.getText(), txtfecha.getText(),micl.getcons_clie(), miv.getIntConsVend(), 
                mic.getcons_cons(), mivh.getcons_vehi(), txtestado.getText());                                                                                                  
       
        jCombof.setSelectedIndex(mif.getcons_clie());
        jCombof.setSelectedIndex(mif.getcons_vend());
        jCombof.setSelectedIndex(mif.getcons_cons());
        jCombof.setSelectedIndex(mif.getcons_vehi());
        txtnumfact.setText(""); // Entrega el valor en los campos de texto  
        txtfecha.setText(""); // Entrega el valor en los campos de texto
        txtestado.setText(""); // Entrega el valor en los campos de texto
   
        
        btnactualizar.setEnabled(false); // Se mantiene el botón actualizar como falso
    }//GEN-LAST:event_btninsertarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        mif.CrudActualizarFactura(mif.getcons_fact(), txtnumfact.getText(), txtfecha.getText(),jCombocl.getSelectedIndex(), 
                jCombov.getSelectedIndex(),jComboc.getSelectedIndex(), jCombovh.getSelectedIndex(), txtestado.getText());
       
        txtnumfact.setText(""); // Entrega el valor en los campos de texto  
        txtfecha.setText(""); // Entrega el valor en los campos de texto
        txtc.setText("");
        txtv.setText("");
        txtcons.setText("");
        txtvh.setText("");
        txtestado.setText(""); // Entrega el valor en los campos de texto
        
        btninsertar.setEnabled(false); // Se mantiene el botón actualizar como falso  
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void jComboclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboclActionPerformed
        // TODO add your handling code here:
        if(cl){
        txtc.setText(jCombocl.getSelectedItem().toString());
        Cliente[] miLista = micl.CrudListaCliente();
        micl = miLista[jCombocl.getSelectedIndex()];

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboclActionPerformed

    private void jCombovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombovActionPerformed
        // TODO add your handling code here:
        if(v){
        txtv.setText(jCombov.getSelectedItem().toString());
        Vendedor[] miLista = miv.crudListaVend();
        miv = miLista[jCombov.getSelectedIndex()];

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jCombovActionPerformed

    private void jCombocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombocActionPerformed
        // TODO add your handling code here:
        if(c){
        txtc.setText(jComboc.getSelectedItem().toString());
        Concesionario[] miLista = mic.crudListaConsecionario();
        mic = miLista[jComboc.getSelectedIndex()];

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jCombocActionPerformed

    private void jCombovhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombovhActionPerformed
        // TODO add your handling code here:
        if(vh){
        txtvh.setText(jCombovh.getSelectedItem().toString());
        Vehiculo[] miLista = mivh.CrudListaVehiculo();
        mivh = miLista[jCombovh.getSelectedIndex()];

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jCombovhActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        f=false; // Se declara la variable booleana como falsa para no realizar la acción       
        txtc.setText(""); // Entrega el valor en los campos de texto
        txtv.setText(""); // Entrega el valor en los campos de texto  
        txtcons.setText(""); // Entrega el valor en los campos de texto
        txtvh.setText(""); // Entrega el valor en los campos de texto
        txtnumfact.setText(""); // Entrega el valor en los campos de texto
        txtfecha.setText(""); // Entrega el valor en los campos de texto
        txtestado.setText(""); // Entrega el valor en los campos de texto

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jCombof.removeAllItems(); //Se limpia el formulario.       
        Factura[] miLista =mif.CrudListaFactura();
        // Se crea un for para borrar el formulario y que el jCombo no este vacio

        for(int intcont=0; intcont < miLista.length; intcont++ ){
        jCombof.addItem(miLista[intcont].getcons_fact()+" - "+ miLista[intcont].getcons_clie()
                +" - "+ miLista[intcont].getcons_vend()+" - "+miLista[intcont].getcons_cons()
                +" - "+ miLista[intcont].getcons_vehi()+" - "+miLista[intcont].getnume_fact()
                +" - "+miLista[intcont].getfech_fact()+" - "+miLista[intcont].getestado()); 
        jCombof.setSelectedIndex(0); // Posiciona el jcombo en la posición 0 
            }           
        f=true;
//.......................................................................................................................
        cl=false; // Se declara la variable booleana como falsa para no realizar la acción

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jCombocl.removeAllItems(); //Se limpia el formulario.
        Cliente[] miLista2 =micl.CrudListaCliente(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista2.length; intcont++ ){
        jCombocl.addItem(miLista2[intcont].getcons_clie()+" - "+miLista2[intcont].getprim_nomb()+" - "
         + miLista2[intcont].getprim_apel()+" - "+miLista2[intcont].getestado());    
        jCombocl.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        cl=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.......................................................................................................................        
        v=false; // Se declara la variable booleana como falsa para no realizar la acción
        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jCombov.removeAllItems(); //Se limpia el formulario.
        Vendedor[] miLista3 =miv.crudListaVend(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista3.length; intcont++ ){
        jCombov.addItem(miLista3[intcont].getIntConsVend()+" - "+miLista3[intcont].getStringNomVend()+" - "+miLista3[intcont].getIntTeleVend()
        +" - "+miLista3[intcont].getestado());    
        jCombov.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        v=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.......................................................................................................................
        c=false; // Se declara la variable booleana como falsa para no realizar la acción

        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboc.removeAllItems(); //Se limpia el formulario.
        Concesionario[] miLista4 =mic.crudListaConsecionario(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista4.length; intcont++ ){
        jComboc.addItem(miLista4[intcont].getcons_cons()+" - "+miLista4[intcont].getnomb_cons()+" - "+miLista4[intcont].getcodi_pobl()
        +" - "+miLista4[intcont].getdire_cons()+" - "+miLista4[intcont].getestado());    
        jComboc.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        
        c=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.........................................................................................................................
        vh=false; // Se declara la variable booleana como falsa para no realizar la acción
        
        btninsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnactualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jCombovh.removeAllItems(); //Se limpia el formulario.
        Vehiculo[] miLista5 =mivh.CrudListaVehiculo(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista5.length; intcont++ ){
        jCombovh.addItem(miLista5[intcont].getcons_vehi()+" - "+miLista5[intcont].getmarc_vehi()+" - "+miLista5[intcont].getmode_vehi()+" - "+miLista5[intcont].getplac_vehi()
        +" - "+miLista5[intcont].getestado());    
        jCombovh.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        
        vh=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
        txtestado.setText(jComboestado.getSelectedItem().toString());
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
        txtc.setText(jCombocl.getSelectedItem().toString());
    }//GEN-LAST:event_txtcActionPerformed

    private void txtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvActionPerformed
        // TODO add your handling code here:
        txtv.setText(jCombov.getSelectedItem().toString());
    }//GEN-LAST:event_txtvActionPerformed

    private void txtconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsActionPerformed
        // TODO add your handling code here:
        txtcons.setText(jComboc.getSelectedItem().toString());
    }//GEN-LAST:event_txtconsActionPerformed

    private void txtvhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvhActionPerformed
        // TODO add your handling code here:
        txtvh.setText(jCombovh.getSelectedItem().toString());
    }//GEN-LAST:event_txtvhActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        mif.CrudBuscarFactura((Integer.parseInt(txtbuscar.getText())));
        
        jCombof.setSelectedIndex(mif.getcons_fact());
        jCombocl.setSelectedIndex(mif.getcons_clie());
        jCombov.setSelectedIndex(mif.getcons_vend());
        jComboc.setSelectedIndex(mif.getcons_cons());
        jCombovh.setSelectedIndex(mif.getcons_vehi());
        txtnumfact.setText(mif.getnume_fact());
        txtfecha.setText(mif.getfech_fact());
        jComboestado.setSelectedIndex(0);
        
        btninsertar.setEnabled(false);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jComboestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboestadoActionPerformed
        // TODO add your handling code here:
        txtestado.setText(jComboestado.getSelectedItem().toString());
    }//GEN-LAST:event_jComboestadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> jComboc;
    private javax.swing.JComboBox<String> jCombocl;
    private javax.swing.JComboBox<String> jComboestado;
    private javax.swing.JComboBox<String> jCombof;
    private javax.swing.JComboBox<String> jCombov;
    private javax.swing.JComboBox<String> jCombovh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtcons;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnumfact;
    private javax.swing.JTextField txtv;
    private javax.swing.JTextField txtvh;
    // End of variables declaration//GEN-END:variables
}
