/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;
import vehiculos.Concesionario;
import vehiculos.Vendedor;

/**
 *
 * @author Toshiba
 */
public class FormVendedor extends javax.swing.JFrame {
    Vendedor miV = new Vendedor();
    Vendedor[] lisTabla = miV.crudListaVend();
    Concesionario miC =new Concesionario();
    Concesionario[] miLista =miC.crudListaConsecionario();//array de marcas
    boolean b, c;
    /**
     * Creates new form FormVendedor
     */
    public FormVendedor() {
        initComponents();
        txtesto.setVisible(false);
        txtcv.setVisible(false);
        txtconsvend.setVisible(false);
        txtcons.setVisible(false);
        b=true;
        
        b=true;
        Concesionario[] miLista =miC.crudListaConsecionario();           
        for(int cont=0; cont < miLista.length; cont++ ){
        jComboC.addItem(miLista[cont].getcons_cons()+" - "+miLista[cont].getnomb_cons());
        }
        
    
        c=true;
        
        c=true;
        Vendedor[] lisTabla = miV.crudListaVend();          
        for(int cont=0; cont < lisTabla.length; cont++ ){
        jComboV.addItem(lisTabla[cont].getIntConsVend()+" - "+lisTabla[cont].getStringNomVend());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnomb = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btninsertar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboC = new javax.swing.JComboBox();
        btnlimpiar = new javax.swing.JButton();
        jComboV = new javax.swing.JComboBox<>();
        btnvolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        txtcons = new javax.swing.JTextField();
        txtconsvend = new javax.swing.JTextField();
        txtcv = new javax.swing.JTextField();
        txtesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vendedor");

        txtnomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Concesionario");

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jComboV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboVActionPerformed(evt);
            }
        });

        btnvolver.setText("Volver");

        jLabel2.setText("Estado");

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "inactivo" }));
        jComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstadoActionPerformed(evt);
            }
        });

        txtcons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsActionPerformed(evt);
            }
        });

        txtconsvend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsvendActionPerformed(evt);
            }
        });

        txtcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcvActionPerformed(evt);
            }
        });

        txtesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btninsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtconsvend, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcons, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcv, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboC, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboV, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtconsvend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsertar)
                    .addComponent(btnactualizar)
                    .addComponent(jButton4)
                    .addComponent(btnlimpiar)
                    .addComponent(btnvolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ListVendedor list =new ListVendedor();
        
        FormVendedor form = new FormVendedor();
        list.setVisible(true);
        
        form .setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        
       miV.crudCrearVendedor(txtnomb.getText(),Integer.parseInt(txttel.getText()),Integer.parseInt(txtconsvend.getText()),jComboEstado.getSelectedItem().toString());
       
       txtcons.setText("");
       txtnomb.setText("");
       txttel.setText("");
       
       
       JOptionPane.showMessageDialog(null, "Se creo el registro", "Creacion de Vendedores",2);//Mensaje de exito (dato 2)
    }//GEN-LAST:event_btninsertarActionPerformed

    private void jComboCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCActionPerformed
        if(b){
        miC = miLista[jComboC.getSelectedIndex()];
        
        
        Concesionario mD = new Concesionario();
        Concesionario[] lD = mD.crudListaConsecionario();
        mD=lD[jComboC.getSelectedIndex()];
        int varInD=mD.getcons_cons();
        }
    }//GEN-LAST:event_jComboCActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        b=false;
       txtnomb.setText("");
       txttel.setText("");
       txtcons.setText("");
       
       jComboV.removeAllItems();
       jComboC.removeAllItems();
       jComboC.repaint();
       jComboV.repaint();
       
        for(int cont=0; cont < miLista.length; cont++ ){
        jComboC.addItem(miLista[cont].getcons_cons()+miLista[cont].getnomb_cons());
        }
        jComboC.setSelectedIndex(0);
        b=true;
        
        for(int cont=0; cont < lisTabla.length; cont++ ){
        jComboV.addItem(lisTabla[cont].getIntConsVend()+lisTabla[cont].getStringNomVend());
        }
        
        jComboV.setSelectedIndex(0);
        b=true;
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtnombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        Realizado e =new Realizado();
        FormVehiculo h = new FormVehiculo();
                
                        e.setVisible(true);
                        h.setVisible(false);
                        setVisible(false);
        miV.crudActualizarVend(Integer.parseInt(txtcv.getText()),txtnomb.getText(),Integer.parseInt(txttel.getText()), Integer.parseInt(txtconsvend.getText()),jComboEstado.getSelectedItem().toString()); //Se importa el método y los parámetros necesarios

        txtnomb.setText("");
        txtcons.setText(""); // Entrega el valor en los campos de texto
        txtcv.setText("");
        txttel.setText("");
        
        
        btninsertar.setEnabled(false); // Se mantiene el botón actualizar como falso  
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void jComboVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboVActionPerformed
        if(b){
        Vendedor[] lisTabla = miV.crudListaVend(); 
        miV = lisTabla[jComboV.getSelectedIndex()];
        
        
        Vendedor mD = new Vendedor();
        Vendedor[] lD = mD.crudListaVend();
        mD=lD[jComboV.getSelectedIndex()];
        int varInD=mD.getIntConsVend();
        
        txtnomb.setText(""+miV.getStringNomVend());
        txttel.setText(""+miV.getIntTeleVend());
        txtcv.setText(""+miV.getIntConsVend());
        txtconsvend.setText(""+miV.getIntConsCons());
        txtesto.setText(""+miV.getestado());
        jComboC.setSelectedIndex(Integer.parseInt(txtconsvend.getText())-1);
        jComboEstado.setSelectedItem(txtesto.getText());
        }
        
    }//GEN-LAST:event_jComboVActionPerformed

    private void jComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstadoActionPerformed
        
    }//GEN-LAST:event_jComboEstadoActionPerformed

    private void txtcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcvActionPerformed

    private void txtconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsActionPerformed

    private void txtestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestoActionPerformed

    private void txtconsvendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsvendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsvendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboC;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JComboBox<String> jComboV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcons;
    private javax.swing.JTextField txtconsvend;
    private javax.swing.JTextField txtcv;
    private javax.swing.JTextField txtesto;
    private javax.swing.JTextField txtnomb;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
