
package Formularios;

import java.awt.Color;
import javax.swing.JOptionPane;
/**
 * /**
 * UNIVERSIDAD DE CUNDINAMARCA
 * Ingenieria de Sistemas
 * Estudiantes: - Ivan Corredor Briceño
 *              - Víctor Pinzón Rodríguez
 * 
 * Profesor: Jorge Páramo Fonseca
 * 
 * @author Víctor Pinzón
 * @version 1.0
 * 
 * Es el formulario superautos y la tabla tbVehiculo
 */
public class Vehiculo extends javax.swing.JFrame {
    tbVehiculo mivehiculo = new tbVehiculo(); //Crear constructor vacio de la clase tbVehiculo
    tbVehiculo [] miListaVh =  mivehiculo.CrudListaVehiculo();

    ctMarca mimarca = new ctMarca();//Crear constructor vacio de la clase ctMarca
    ctMarca [] miListaM = mimarca.CrudListaMarca();
    
    ctEstilo miestilo = new ctEstilo();//Crear constructor vacio de la clase ctEstilo
    ctEstilo [] miListaE = miestilo.CrudListaEstilo();
    
    ctColor micolor = new ctColor();//Crear constructor vacio de la clase ctColor
    ctColor [] miListaC = micolor.CrudListaColor();
    
    ctTipoCombustible mitcombustible = new ctTipoCombustible();//Crear constructor vacio de la clase ctTipoCombustible
    ctTipoCombustible [] miListaTC = mitcombustible.CrudListaTipoCombustible();
    
    boolean p,bm,be,bc,btc;
    /**
     * Creates new form FormVehiculo
     */
    
    public Vehiculo() {
        initComponents();
        this.setLocation(300,120);//En esta instancia(this)cambiar(set)la posición(Location)
        this.setSize(540,480);
    
//.................................
        //Contador del formulario   
        p=true;
        for(int intcont=0; intcont < miListaVh.length; intcont++ ){
        jComboVh.addItem(miListaVh[intcont].getintIdVehiculo()+" - "+ miListaVh[intcont].getintIdMarca() 
                +" - "+ miListaVh[intcont].getintIdEstilo()+" - "+miListaVh[intcont]
                +" - "+ miListaVh[intcont].getintTipoCombustible()+" - "+miListaVh[intcont].getintPrecio()
                +" - "+miListaVh[intcont].getstrPlaca()+" - "+miListaVh[intcont].getstrNumeroChasis()
                +" - "+miListaVh[intcont].getstrNumeroMotor()+" - "+miListaVh[intcont].getstrCilindraje()
                +" - "+miListaVh[intcont].getstrModelo()+" - "+miListaVh[intcont].getstrVersion());                
            }
        
        bm=true;
        for(int intcont=0; intcont < miListaM.length; intcont++ ){
        jComboM.addItem(miListaM[intcont].getintIdMarca()+" - "+miListaM[intcont].getstrNombreMarca()+" - "
         + miListaM[intcont].getstrSiglasMarca());  
            }
        
        be=true;        
        for(int intcont=0; intcont < miListaE.length; intcont++ ){
        jComboE.addItem(miListaE[intcont].getstrTipoEstilo());  

            }
        
        bc=true;
        for(int intcont=0; intcont < miListaC.length; intcont++ ){
        jComboC.addItem(miListaC[intcont].getintIdColor()+" - "+miListaC[intcont].getstrNombreColor());

            }
        
        btc=true;
        for(int intcont=0; intcont < miListaTC.length; intcont++ ){
        jComboTC.addItem(miListaTC[intcont].getintTipoCombustible()+" - "+miListaTC[intcont].getstrNombreTipoCombustible());    

            }
        }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboVh = new javax.swing.JComboBox();
        txtPlaca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNumChasis = new javax.swing.JTextField();
        txtNumMotor = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtCilindraje = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtVersion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jComboM = new javax.swing.JComboBox();
        jComboE = new javax.swing.JComboBox();
        jComboC = new javax.swing.JComboBox();
        jComboTC = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Vehiculo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 47, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(37, 69, 35, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Estilo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(257, 69, 30, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Color");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 131, 29, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Tipo Combustible");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(251, 131, 97, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Placa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 204, 30, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Precio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 194, 35, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("# Chasis");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 254, 48, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("# Motor");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 254, 46, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Cilindraje");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 314, 53, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("Modelo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(180, 314, 41, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Versión");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 314, 42, 14);

        jComboVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboVhActionPerformed(evt);
            }
        });
        getContentPane().add(jComboVh);
        jComboVh.setBounds(90, 20, 274, 20);

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlaca);
        txtPlaca.setBounds(70, 194, 80, 30);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(220, 194, 200, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 50, 463, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 107, 463, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 166, 463, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(30, 234, 463, 10);
        getContentPane().add(txtNumChasis);
        txtNumChasis.setBounds(80, 254, 80, 30);

        txtNumMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumMotorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumMotor);
        txtNumMotor.setBounds(230, 254, 80, 30);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(30, 294, 463, 10);
        getContentPane().add(txtCilindraje);
        txtCilindraje.setBounds(90, 314, 80, 30);
        getContentPane().add(txtModelo);
        txtModelo.setBounds(230, 314, 80, 30);

        txtVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVersionActionPerformed(evt);
            }
        });
        getContentPane().add(txtVersion);
        txtVersion.setBounds(370, 314, 80, 30);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(30, 354, 463, 10);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar);
        btnInsertar.setBounds(30, 374, 71, 23);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(120, 374, 79, 23);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(220, 374, 65, 23);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(430, 374, 63, 23);

        jComboM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMActionPerformed(evt);
            }
        });
        getContentPane().add(jComboM);
        jComboM.setBounds(82, 69, 155, 30);

        jComboE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEActionPerformed(evt);
            }
        });
        getContentPane().add(jComboE);
        jComboE.setBounds(295, 69, 155, 30);

        jComboC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCActionPerformed(evt);
            }
        });
        getContentPane().add(jComboC);
        jComboC.setBounds(83, 128, 150, 30);

        jComboTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTCActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTC);
        jComboTC.setBounds(358, 128, 149, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/fondo-rojo-5634.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboVhActionPerformed
        // TODO add your handling code here:
        if(p){
        tbVehiculo[] miLista = mivehiculo.CrudListaVehiculo();
        mivehiculo = miLista[jComboVh.getSelectedIndex()];

        txtPrecio.setText(" " + mivehiculo.getintPrecio());
        txtPlaca.setText(" " + mivehiculo.getstrPlaca());
        txtNumChasis.setText(" " + mivehiculo.getstrNumeroChasis());
        txtNumMotor.setText(" " + mivehiculo.getstrNumeroMotor());
        txtCilindraje.setText(" " + mivehiculo.getstrCilindraje());
        txtModelo.setText(" " + mivehiculo.getstrModelo());
        txtVersion.setText(" " + mivehiculo.getstrVersion());
        
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboVhActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNumMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumMotorActionPerformed

    private void txtVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVersionActionPerformed
        // TODO addd your handling code here:
    }//GEN-LAST:event_txtVersionActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        
        mivehiculo.CrudInsertarVehiculo(mimarca.getintIdMarca(), miestilo.getintIdEstilo(), 
                micolor.getintIdColor(), mitcombustible.getintTipoCombustible(), 
                Integer.parseInt(txtPrecio.getText()), txtPlaca.getText(), txtNumChasis.getText(), txtNumMotor.getText(), 
                txtCilindraje.getText(), txtModelo.getText(), txtVersion.getText());                                                                                                  
       
        jComboVh.setSelectedIndex(mivehiculo.getintIdMarca());
        jComboVh.setSelectedIndex(mivehiculo.getintIdEstilo());
        jComboVh.setSelectedIndex(mivehiculo.getintIdColor());
        jComboVh.setSelectedIndex(mivehiculo.getintTipoCombustible());
        txtPrecio.setText(""); // Entrega el valor en los campos de texto  
        txtPlaca.setText(""); // Entrega el valor en los campos de texto
        txtNumChasis.setText(""); // Entrega el valor en los campos de texto
        txtNumMotor.setText(""); // Entrega el valor en los campos de texto
        txtCilindraje.setText(""); // Entrega el valor en los campos de texto
        txtModelo.setText(""); // Entrega el valor en los campos de texto
        txtVersion.setText(""); // Entrega el valor en los campos de texto
        
        btnActualizar.setEnabled(false); // Se mantiene el botón actualizar como falso
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here: 
        
        mivehiculo.CrudActualizarVehiculo(mivehiculo.getintIdVehiculo(),mimarca.getintIdMarca(), miestilo.getintIdEstilo(), 
                micolor.getintIdColor(), mitcombustible.getintTipoCombustible(),
                Integer.parseInt(txtPrecio.getText()),txtPlaca.getText(), txtNumChasis.getText(),txtNumMotor.getText(), 
                txtCilindraje.getText(), txtModelo.getText(), 
                txtVersion.getText()); //Se importa el método y los parámetros necesarios

        jComboM.setSelectedIndex(mivehiculo.getintIdMarca());
        jComboE.setSelectedIndex(mivehiculo.getintIdEstilo());
        jComboC.setSelectedIndex(mivehiculo.getintIdColor());
        jComboTC.setSelectedIndex(mivehiculo.getintTipoCombustible());
        txtPlaca.setText(""); // Entrega el valor en los campos de texto
        txtPrecio.setText(""); // Entrega el valor en los campos de texto  
        txtNumChasis.setText(""); // Entrega el valor en los campos de texto
        txtNumMotor.setText(""); // Entrega el valor en los campos de texto
        txtCilindraje.setText(""); // Entrega el valor en los campos de texto
        txtModelo.setText(""); // Entrega el valor en los campos de texto
        txtVersion.setText(""); // Entrega el valor en los campos de texto
        
        btnInsertar.setEnabled(false); // Se mantiene el botón actualizar como falso  
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jComboTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTCActionPerformed
        // TODO add your handling code here:
        if(btc){
        ctTipoCombustible[] miLista = mitcombustible.CrudListaTipoCombustible();
        mitcombustible = miLista[jComboTC.getSelectedIndex()];

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboTCActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        p=false; // Se declara la variable booleana como falsa para no realizar la acción       
        txtPlaca.setText(""); // Entrega el valor en los campos de texto
        txtPrecio.setText(""); // Entrega el valor en los campos de texto  
        txtNumChasis.setText(""); // Entrega el valor en los campos de texto
        txtNumMotor.setText(""); // Entrega el valor en los campos de texto
        txtCilindraje.setText(""); // Entrega el valor en los campos de texto
        txtModelo.setText(""); // Entrega el valor en los campos de texto
        txtVersion.setText(""); // Entrega el valor en los campos de texto

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboVh.removeAllItems(); //Se limpia el formulario.       
        tbVehiculo[] miLista =mivehiculo.CrudListaVehiculo(); 
        // Se crea un for para borrar el formulario y que el jCombo no este vacio

        for(int intcont=0; intcont < miLista.length; intcont++ ){
        jComboVh.addItem(miLista[intcont].getintIdVehiculo()+" - "+ miLista[intcont].getintIdMarca() 
                +" - "+ miLista[intcont].getintIdEstilo()+" - "+miLista[intcont].getintIdColor()
                +" - "+ miLista[intcont].getintTipoCombustible()+" - "+miLista[intcont].getintPrecio()
                +" - "+miLista[intcont].getstrPlaca()+" - "+miLista[intcont].getstrNumeroChasis()
                +" - "+miLista[intcont].getstrNumeroMotor()+" - "+miLista[intcont].getstrCilindraje()
                +" - "+miLista[intcont].getstrModelo()+" - "+miLista[intcont].getstrVersion()); 
        jComboVh.setSelectedIndex(0); // Posiciona el jcombo en la posición 0 
            }           
        p=true;
//.......................................................................................................................
        bm=false; // Se declara la variable booleana como falsa para no realizar la acción

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboM.removeAllItems(); //Se limpia el formulario.
        ctMarca[] miLista2 =mimarca.CrudListaMarca(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista2.length; intcont++ ){
        jComboM.addItem(miLista2[intcont].getintIdMarca()+" - "+miLista2[intcont].getstrNombreMarca()+" - "
         + miLista2[intcont].getstrSiglasMarca());    
        jComboM.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        bm=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.......................................................................................................................        
        be=false; // Se declara la variable booleana como falsa para no realizar la acción
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboE.removeAllItems(); //Se limpia el formulario.
        ctEstilo[] miLista3 =miestilo.CrudListaEstilo(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista3.length; intcont++ ){
        jComboE.addItem(miLista3[intcont].getintIdEstilo()+" - "+miLista3[intcont].getstrTipoEstilo());    
        jComboE.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        be=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.......................................................................................................................
        bc=false; // Se declara la variable booleana como falsa para no realizar la acción

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboC.removeAllItems(); //Se limpia el formulario.
        ctColor[] miLista4 =micolor.CrudListaColor(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista4.length; intcont++ ){
        jComboC.addItem(miLista4[intcont].getintIdColor()+" - "+miLista4[intcont].getstrNombreColor());    
        jComboC.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        
        bc=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
//.........................................................................................................................
        btc=false; // Se declara la variable booleana como falsa para no realizar la acción
        
        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
       
        jComboTC.removeAllItems(); //Se limpia el formulario.
        ctTipoCombustible[] miLista5 =mitcombustible.CrudListaTipoCombustible(); 
         
        // Se crea un for para borrar el formulario y que el jCombo no este vacio
        for(int intcont=0; intcont < miLista5.length; intcont++ ){
        jComboTC.addItem(miLista5[intcont].getintTipoCombustible()+" - "+miLista5[intcont].getstrNombreTipoCombustible());    
        jComboTC.setSelectedIndex(0); // Posiciona el jcombo en la posició 0
            }
        
        btc=true; // Se declara la variable booleana como verdadera para que luego se pueda realizar la acción
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jComboMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMActionPerformed
        // TODO add your handling code here:
        if(bm){
        ctMarca[] miLista = mimarca.CrudListaMarca();
        mimarca = miLista[jComboM.getSelectedIndex()];

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboMActionPerformed

    private void jComboEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEActionPerformed
        // TODO add your handling code here:
        if(be){
        ctEstilo[] miLista = miestilo.CrudListaEstilo();
        miestilo = miLista[jComboE.getSelectedIndex()];

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboEActionPerformed

    private void jComboCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCActionPerformed
        // TODO add your handling code here:
        if(bc){
        ctColor[] miLista = micolor.CrudListaColor();
        micolor = miLista[jComboC.getSelectedIndex()];

        btnInsertar.setEnabled(true); // Se mantiene el botón insertar como verdadero
        btnActualizar.setEnabled(true); // Se mantiene el botón actualizar como verdadero
        }
    }//GEN-LAST:event_jComboCActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
            FormRegistrovehiculos Fmenu =  new FormRegistrovehiculos();
            Fmenu.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox jComboC;
    private javax.swing.JComboBox jComboE;
    private javax.swing.JComboBox jComboM;
    private javax.swing.JComboBox jComboTC;
    private javax.swing.JComboBox jComboVh;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumChasis;
    private javax.swing.JTextField txtNumMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
